# generated by jqsh:jqsh:as-lib, avoid edit
shopt -s expand_aliases
alias EJQ='ns:EJQ'
alias p1='EJQ:p1'
alias p2='EJQ:p2'
alias pretty='EJQ:pretty'
alias ejq='EJQ:ejq'
EJQ:ejq () 
{ 
    local id=ejq;
    local ns=EJQ;
    yq -oj | EJQ:p1 | EJQ:p2 | EJQ:pretty | jq -nf /dev/stdin
}
EJQ:p1 () 
{ 
    local id=p1;
    local ns=EJQ;
    local jq='def data: { data: (reduce (.. | objects | select(has("data"))) as $data ({}; . * $data) | .data) };
def body: { body: delpaths([path(.. | objects | select(has("data")))]) };
def jq(t): ("jq" + t) as $jq | { ($jq): (body | [ path(.. | objects | select(has($jq))) as $p | [ $p, getpath($p)[$jq] ]]) };
data + body + jq("e") + jq("d")';
    jqsh:self "$@"
}
EJQ:p2 () 
{ 
    local id=p2;
    local ns=EJQ;
    local jq='def emit(t): ("jq" + t) as $jq | .[$jq] | if t == "d" then map(last + " .") else map("setpath(\(first); $data | \(last))") end;
tojson + "\n | .data as $data | " + (emit("d") + emit("e") | join(" | ") + ".body | delpaths([path(.. | objects | select(has(\"jqd\")))])[0]")';
    jqsh:self -r
}
EJQ:pretty () 
{ 
    local id=pretty;
    local ns=EJQ;
    awk 'NR == 1 { print | "jq"; close("jq"); } NR != 1'
}
ns:EJQ () 
{ 
    EJQ:${1:?} "${@:2}"
}
jqsh:self () 
{ 
    local id=self;
    local ns=jqsh;
    jq "$jq" "$@"
}
eval "$@"
