# generated by jqsh:jqsh:as-lib, avoid edit
shopt -s expand_aliases
alias git2md='ns:git2md'
alias check-tty='git2md:check-tty'
alias relative-file-to-js='git2md:relative-file-to-js'
alias git-file-to-url='git2md:git-file-to-url'
alias git-repo-to-md='git2md:git-repo-to-md'
alias git-site='git2md:git-site'
alias git-repo-to-js='git2md:git-repo-to-js'
alias git-url='git2md:git-url'
alias relative-file-to-md='git2md:relative-file-to-md'
alias git-repo-to-url='git2md:git-repo-to-url'
alias git-commit-to-js='git2md:git-commit-to-js'
alias git-branch-or-tag='git2md:git-branch-or-tag'
alias gr2md='git2md:gr2md'
alias git-url-to-md='git2md:git-url-to-md'
alias git-repo='git2md:git-repo'
alias git-commit-to-md='git2md:git-commit-to-md'
alias git-repo-and-commit-to-js='git2md:git-repo-and-commit-to-js'
alias git-file-to-md='git2md:git-file-to-md'
alias gc2md='git2md:gc2md'
alias gf2md='git2md:gf2md'
git2md:check-tty () 
{ 
    local id=check-tty;
    local ns=git2md;
    [ -t 0 ] && jqsh:fail "input shouldn't be a TTY"
}
git2md:gc2md () 
{ 
    local id=gc2md;
    local ns=git2md;
    git2md:git-commit-to-md "$@"
}
git2md:gf2md () 
{ 
    local id=gf2md;
    local ns=git2md;
    git2md:git-file-to-md "$@"
}
git2md:git-branch-or-tag () 
{ 
    local id=git-branch-or-tag;
    local ns=git2md;
    if [ "$1" ]; then
        git tag | grep $1 || jqsh:fail no $1 tag;
    else
        git branch --show-current;
    fi
}
git2md:git-commit-to-js () 
{ 
    local id=git-commit-to-js;
    local ns=git2md;
    pretty='{ _XXX_comment_XXX_: _XXX_%s_XXX_, _XXX_commit_XXX_: _XXX_%H_XXX_ }';
    git log -${1:-1} --pretty="$pretty" | sed -e 's/"/\\"/g' -e 's/_XXX_/"/g'
}
git2md:git-commit-to-md () 
{ 
    local id=git-commit-to-md;
    local ns=git2md;
    local jq='"\n    " as $s | "[\(.comment)]:\($s)\(.url)/commit/\(.commit)\($s)\"github.com commit\"\n"';
    git2md:git-repo-and-commit-to-js "$@" | jqsh:self -r;
    alias gc2md=$id
}
git2md:git-file-to-md () 
{ 
    local id=git-file-to-md;
    local ns=git2md;
    git2md:check-tty;
    git2md:git-file-to-url "$@" | git2md:git-url-to-md
}
git2md:git-file-to-url () 
{ 
    local id=git-file-to-url;
    local ns=git2md;
    xargs -ri echo https://$(git-site)/$(git-repo)/blob/$(git-branch-or-tag "$@")/{}
}
git2md:git-repo () 
{ 
    local id=git-repo;
    local ns=git2md;
    local jq='split(":")[1]';
    git2md:git-url | jqsh:self -Rr
}
git2md:git-repo-and-commit-to-js () 
{ 
    local id=git-repo-and-commit-to-js;
    local ns=git2md;
    local jq='input as $r | [inputs] | map([$r, .] | add)[]';
    { 
        git2md:git-repo-to-js;
        git2md:git-commit-to-js "$@"
    } | jqsh:self -n
}
git2md:git-repo-to-js () 
{ 
    local id=git-repo-to-js;
    local ns=git2md;
    local jq='{ url: .}';
    git2md:git-repo-to-url | jqsh:self -R
}
git2md:git-repo-to-md () 
{ 
    local id=git-repo-to-md;
    local ns=git2md;
    git2md:git-repo-to-url | git2md:git-url-to-md repo
}
git2md:git-repo-to-url () 
{ 
    local id=git-repo-to-url;
    local ns=git2md;
    local jq='[inputs] | "https://\(first)/\(last)"';
    { 
        git2md:git-site;
        git2md:git-repo
    } | jqsh:self -nRr
}
git2md:git-site () 
{ 
    local id=git-site;
    local ns=git2md;
    local jq='split(":")[0]|split("@")[1]';
    git2md:git-url | jqsh:self -Rr
}
git2md:git-url () 
{ 
    local id=git-url;
    local ns=git2md;
    git config --get remote.origin.url
}
git2md:git-url-to-md () 
{ 
    local id=git-url-to-md;
    local ns=git2md;
    local jq='"\n    " as $s
| (if $what == "repo" then split("/")[-1] else split("/")[7:] | join("/") end) as $p
| "[\($p)]:\($s)\(.)\($s)\"github.com \($what)\"\n"';
    jqsh:self -Rr --arg what ${1:-file}
}
git2md:gr2md () 
{ 
    local id=gr2md;
    local ns=git2md;
    git2md:git-repo-to-md "$@"
}
git2md:relative-file-to-js () 
{ 
    local id=relative-file-to-js;
    local ns=git2md;
    local jq='{ url: ., name: . }';
    jqsh:self -R
}
git2md:relative-file-to-md () 
{ 
    local id=relative-file-to-md;
    local ns=git2md;
    local jq='"\n    " as $s | "[\(.name)]:\($s)\(.url)\($s)\"github.com relative file\"\n"';
    git2md:check-tty;
    git2md:relative-file-to-js | jqsh:self -r
}
ns:git2md () 
{ 
    git2md:${1:?} "${@:2}"
}
jqsh:self () 
{ 
    local id=self;
    local ns=jqsh;
    jq "$jq" "$@"
}
eval "$@"
