# generated by jqsh:jqsh:as-lib, avoid edit
shopt -s expand_aliases
alias jqsh='ns:jqsh'
alias nsp='jqsh:nsp'
alias forget='jqsh:forget'
alias lib='jqsh:lib'
alias nss='jqsh:nss'
alias map='jqsh:map'
alias nss1='jqsh:nss1'
alias optal='jqsh:optal'
alias ns='jqsh:ns'
alias tst='jqsh:tst'
alias aliases1='jqsh:aliases1'
alias fn='jqsh:fn'
alias forget1='jqsh:forget1'
alias lib1='jqsh:lib1'
alias listid1='jqsh:listid1'
alias list='jqsh:list'
alias txt='jqsh:txt'
alias warn='jqsh:warn'
alias aliases='jqsh:aliases'
alias fail='jqsh:fail'
alias def='jqsh:def'
alias self='jqsh:self'
alias as-lib='jqsh:as-lib'
alias load='jqsh:load'
alias listid='jqsh:listid'
alias as-cmd='jqsh:as-cmd'
alias def1='jqsh:def1'
alias with-lib='jqsh:with-lib'
alias loop='jqsh:loop'
alias txt1='jqsh:txt1'
alias args='jqsh:args'
alias fn1='jqsh:fn1'
jqsh:alias () 
{ 
    if [[ ! -v BASH_ALIASES[$1] || -v BASH_ALIASES[$1] && BASH_ALIASES[$1] != $2:$1 ]]; then
        alias $1=$2:$1;
    else
        echo warning $(alias $1) 1>&2;
    fi
}
jqsh:aliases () 
{ 
    local id=aliases;
    local ns=jqsh;
    jqsh:loop $ns:aliases1 "$@"
}
jqsh:aliases1 () 
{ 
    local id=aliases1;
    local ns=jqsh;
    local jq='$ARGS.positional | [.[:$n], .[$n:]] | transpose[] | select(last | test("\($ns):")) | first';
    jqsh:nsp ${1:?} || jqsh:fail not a ns;
    jqsh:self -nr --arg ns $1 --argjson n ${#BASH_ALIASES[@]} --args "${!BASH_ALIASES[@]}" "${BASH_ALIASES[@]}"
}
jqsh:args () 
{ 
    local id=args;
    local ns=jqsh;
    mapfile -t;
    ((${#MAPFILE[@]} > 0)) && "${@:-echo}" "${MAPFILE[@]}"
}
jqsh:as-cmd () 
{ 
    local id=as-cmd;
    local ns=jqsh;
    jqsh:as-lib "$@";
    echo 'eval "$@"'
}
jqsh:as-lib () 
{ 
    local id=as-lib;
    local ns=jqsh;
    jqsh:warn;
    jqsh:lib "$@"
}
jqsh:def () 
{ 
    local id=def;
    local ns=jqsh;
    jqsh:loop $ns:def1 "$@"
}
jqsh:def1 () 
{ 
    local id=def1;
    local ns=jqsh;
    [[ -v BASH_ALIASES[${1:?}] ]] || jqsh:fail $1 not an alias && declare -f ${BASH_ALIASES[$1]}
}
jqsh:fail () 
{ 
    local id=fail;
    local ns=jqsh;
    unset -v fail;
    : "${fail:?${FUNCNAME[1]} $@}"
}
jqsh:fn () 
{ 
    local id=fn;
    local ns=jqsh;
    jqsh:loop $ns:fn1 "$@"
}
jqsh:fn1 () 
{ 
    local id=fn1;
    local ns=jqsh;
    jqsh:listid1 ${1:?} | jqsh:args declare -f
}
jqsh:forget () 
{ 
    local id=forget;
    local ns=jqsh;
    jqsh:loop $ns:${id}1 "$@"
}
jqsh:forget1 () 
{ 
    local id=forget1;
    local ns=jqsh;
    . <($ns:listid1 ${1:?} | args echo unset -f; nsp $1 && { aliases $1 | args echo unalias; echo unalias $1; })
}
jqsh:lib () 
{ 
    local id=lib;
    local ns=jqsh;
    jqsh:optal;
    jqsh:loop $ns:lib1 "$@";
    jqsh:def self
}
jqsh:lib1 () 
{ 
    local id=lib1;
    local ns=jqsh;
    jqsh:nsp ${1:?} || jqsh:fail not a ns;
    alias $1;
    alias $(aliases $1);
    jqsh:fn $1
}
jqsh:list () 
{ 
    local id=list;
    local ns=jqsh;
    jqsh:loop echo "$@"
}
jqsh:listid () 
{ 
    local id=listid;
    local ns=jqsh;
    jqsh:loop $ns:${id}1 "$@"
}
jqsh:listid1 () 
{ 
    local id=listid1;
    local ns=jqsh;
    compgen -c ${1:?}:;
    compgen -c ns:${1:?}
}
jqsh:load () 
{ 
    local id=load;
    local ns=jqsh;
    jqsh:forget $(nss "$@");
    . <($ns:txt "$@")
}
jqsh:loop () 
{ 
    local id=loop;
    local ns=jqsh;
    local i;
    for i in "${@:2}";
    do
        $1 $i;
    done
}
jqsh:map () 
{ 
    local id=map;
    local ns=jqsh;
    while read; do
        "${@:-echo}" "$REPLY";
    done
}
jqsh:ns () 
{ 
    local id=ns;
    local ns=jqsh;
    compgen -c ns:
}
jqsh:nsp () 
{ 
    local id=nsp;
    local ns=jqsh;
    compgen -c ns:${1:?} > /dev/null
}
jqsh:nss () 
{ 
    local id=nss;
    local ns=jqsh;
    jqsh:loop $ns:${id}1 "$@"
}
jqsh:nss1 () 
{ 
    local id=nss1;
    local ns=jqsh;
    local jq='.[].ns // empty';
    yq -oj < ${1:?} | jqsh:self -r
}
jqsh:optal () 
{ 
    local id=optal;
    local ns=jqsh;
    echo shopt -s expand_aliases
}
jqsh:self () 
{ 
    local id=self;
    local ns=jqsh;
    jq "$jq" "$@"
}
jqsh:tst () 
{ 
    local id=tst;
    local ns=jqsh;
    < ${1:?}
}
jqsh:txt () 
{ 
    local id=txt;
    local ns=jqsh;
    jqsh:loop $ns:tst "$@" && yq -oj "$@" | jq -s add | jqsh:txt1
}
jqsh:txt1 () 
{ 
    local id=txt1;
    local ns=jqsh;
    dist.jq --args ns | jsm4.jq | m4 -P | jqsh.jq
}
jqsh:warn () 
{ 
    local id=warn;
    local ns=jqsh;
    echo \# generated by $ns:${FUNCNAME[1]}, avoid edit
}
jqsh:with-lib () 
{ 
    local id=with-lib;
    local ns=jqsh;
    (($#)) || jqsh:fail $id;
    jqsh:optal;
    until [[ $# == 0 || $1 == -- ]]; do
        jqsh:lib1 $1;
        shift;
    done;
    [[ $1 == -- ]] && shift;
    jqsh:def self;
    (($#)) && { 
        f=${BASH_ALIASES[$1]:-$1};
        shift;
        echo $f "${@@Q}"
    }
}
ns:jqsh () 
{ 
    jqsh:${1:?} "${@:2}"
}
jqsh:self () 
{ 
    local id=self;
    local ns=jqsh;
    jq "$jq" "$@"
}
eval "$@"
