# generated by jqsh:jqsh:as-lib, avoid edit
shopt -s expand_aliases
alias std='ns:std'
alias inter='std:inter'
std:inter () 
{ 
    local id=inter;
    local ns=std;
    local jq='def inter:
  if type != "array" then error("want array \($__loc__)")
  elif length == 0 then error("empty array \($__loc__)")
  elif map(type == "array") | all | not then error("want array of arrays\($__loc__)")
  elif length == 1 then .[0]
  elif length == 2 then .[0] - (.[0] - .[1])
  else [(.[:2] | inter), (.[2:] | inter)] | inter end; inter';
    jqsh:self "$@"
}
ns:std () 
{ 
    std:${1:?} "${@:2}"
}
jqsh:self () 
{ 
    local id=self;
    local ns=jqsh;
    jq "$jq" "$@"
}
eval "$@"
